// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.2
// source: backend/v1/rank.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRankServiceGetRankList = "/kob_kratos.v1.RankService/GetRankList"

type RankServiceHTTPServer interface {
	GetRankList(context.Context, *GetRankListRequest) (*GetRankListResponse, error)
}

func RegisterRankServiceHTTPServer(s *http.Server, srv RankServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/rank/getlist", _RankService_GetRankList0_HTTP_Handler(srv))
}

func _RankService_GetRankList0_HTTP_Handler(srv RankServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRankListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRankServiceGetRankList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRankList(ctx, req.(*GetRankListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRankListResponse)
		return ctx.Result(200, reply)
	}
}

type RankServiceHTTPClient interface {
	GetRankList(ctx context.Context, req *GetRankListRequest, opts ...http.CallOption) (rsp *GetRankListResponse, err error)
}

type RankServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRankServiceHTTPClient(client *http.Client) RankServiceHTTPClient {
	return &RankServiceHTTPClientImpl{client}
}

func (c *RankServiceHTTPClientImpl) GetRankList(ctx context.Context, in *GetRankListRequest, opts ...http.CallOption) (*GetRankListResponse, error) {
	var out GetRankListResponse
	pattern := "/api/rank/getlist"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRankServiceGetRankList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
