// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kob-kratos/app/backend/internal/biz"
	"kob-kratos/app/backend/internal/conf"
	"kob-kratos/app/backend/internal/data"
	"kob-kratos/app/backend/internal/server"
	"kob-kratos/app/backend/internal/service/bot"
	"kob-kratos/app/backend/internal/service/rank"
	"kob-kratos/app/backend/internal/service/record"
	"kob-kratos/app/backend/internal/service/user"
	"kob-kratos/app/backend/internal/service/ws"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, jwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewPostgresDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := data.NewUserRepository(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepository, logger, jwt)
	service := user.NewService(userUsecase, logger)
	recordRepository := data.NewRecordRepository(dataData, logger)
	recordUsecase := biz.NewRecordUsecase(recordRepository, logger)
	recordService := record.NewService(recordUsecase, logger)
	rankRepository := data.NewRankRepository(dataData, logger)
	rankUsecase := biz.NewRankUsecase(rankRepository, logger)
	rankService := rank.NewService(rankUsecase, logger)
	botRepository := data.NewBotRepository(dataData, logger)
	botUsecase := biz.NewBotUsecase(botRepository, logger)
	botService := bot.NewService(botUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, service, recordService, rankService, botService, logger)
	hub := ws.NewHub(logger)
	handler := server.NewWsRouter(hub, logger)
	httpServer := server.NewHTTPServer(bootstrap, service, recordService, rankService, botService, handler, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
