// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kob-kratos/internal/biz"
	"kob-kratos/internal/conf"
	"kob-kratos/internal/server"
	"kob-kratos/internal/service/bot"
	"kob-kratos/internal/service/rank"
	"kob-kratos/internal/service/record"
	"kob-kratos/internal/service/user"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userUsecase := biz.NewUserUsecase(logger)
	service := user.NewService(userUsecase, logger)
	recordUsecase := biz.NewRecordUsecase(logger)
	recordService := record.NewService(recordUsecase, logger)
	rankUsecase := biz.NewRankUsecase(logger)
	rankService := rank.NewService(rankUsecase, logger)
	botUsecase := biz.NewBotUsecase(logger)
	botService := bot.NewService(botUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, service, recordService, rankService, botService, logger)
	httpServer := server.NewHTTPServer(confServer, service, recordService, rankService, botService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
