// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBot = "bot"

// Bot mapped from table <bot>
type Bot struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32          `gorm:"column:user_id;not null;index:idx_bot_user_id,priority:1;index:idx_bot_user_created_at,priority:2" json:"user_id"`
	Title       string         `gorm:"column:title;not null;index:idx_bot_title,priority:1" json:"title"`
	Description *string        `gorm:"column:description" json:"description"`
	Code        string         `gorm:"column:code;not null" json:"code"`
	CreatedAt   *time.Time     `gorm:"column:created_at;index:idx_bot_user_created_at,priority:1;index:idx_bot_created_at,priority:1" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Bot's table name
func (*Bot) TableName() string {
	return TableNameBot
}
