// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRecord = "record"

// Record mapped from table <record>
type Record struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AID       int32          `gorm:"column:a_id;not null;index:idx_record_players,priority:1;index:idx_record_a_id_created_at,priority:1" json:"a_id"`
	ASx       int32          `gorm:"column:a_sx;not null" json:"a_sx"`
	ASy       int32          `gorm:"column:a_sy;not null" json:"a_sy"`
	BID       int32          `gorm:"column:b_id;not null;index:idx_record_players,priority:2;index:idx_record_b_id_created_at,priority:1" json:"b_id"`
	BSx       int32          `gorm:"column:b_sx;not null" json:"b_sx"`
	BSy       int32          `gorm:"column:b_sy;not null" json:"b_sy"`
	ASteps    string         `gorm:"column:a_steps;not null" json:"a_steps"`
	BSteps    string         `gorm:"column:b_steps;not null" json:"b_steps"`
	GameMap   string         `gorm:"column:game_map;not null" json:"game_map"`
	LoserName string         `gorm:"column:loser_name;not null" json:"loser_name"`
	LoserID   int64          `gorm:"column:loser_id;not null;index:idx_record_loser,priority:1" json:"loser_id"`
	CreatedAt *time.Time     `gorm:"column:created_at;index:idx_record_b_id_created_at,priority:2;index:idx_record_created_at,priority:1;index:idx_record_a_id_created_at,priority:2" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
