// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kob-kratos/app/matching/internal/biz"
	"kob-kratos/app/matching/internal/biz/matchpool"
	"kob-kratos/app/matching/internal/conf"
	"kob-kratos/app/matching/internal/data"
	server2 "kob-kratos/app/matching/internal/server"
	"kob-kratos/app/matching/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewPostgresDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := data.NewUserRepository(dataData, logger)
	matchPool := server.NewMatchPool()
	matchUsecase := biz.NewMatchUsecase(logger, userRepository, matchPool)
	matchingSystemService := service.NewMatchingSystemService(matchUsecase)
	grpcServer := server2.NewGRPCServer(confServer, logger, matchingSystemService)
	httpServer := server2.NewHTTPServer(bootstrap, logger)
	app := newApp(logger, grpcServer, httpServer, matchPool)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
